# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ORxavUqhJPzrElJbWIgcqZ2sxf0S9OVb
"""

import sympy as sp
from matplotlib import pyplot as plt
import numpy as np

x, A = sp.symbols('x A')
A = 45
f1 = x**2 - (2 * A * x) - (A**2)
f2 = -(x**2) + (4 * A * x) + (A**3)

giai = sp.solve([f1 - f2], x)
x1 = giai[0][0]
x2 = giai[1][0]

y1 = f1.subs(x, x1)
y2 = f2.subs(x, x2)


x1_float = x1.evalf()
y1_float = y1.evalf()
x2_float = x2.evalf()
y2_float = y2.evalf()


print("1a. Intersection point 1 :","(", x1_float, y1_float,")")
print("1a. Intersection point 2 :","(", x2_float, y2_float,")")

x = np.arange(-1100, 1300)
f1_1 = lambda x: (x**2) - (2 * A * x) - (A**2)
f2_1 = lambda x: -(x**2) + (4 * A * x) + (A**3)
y1 = list(map(f1_1, x))
y2 = list(map(f2_1, x))

plt.plot(x, y1, label='y = f(x)')
plt.plot(x, y2, label='y = g(x)')

plt.plot(x1_float, y1_float, 'ro')
plt.plot(x2_float, y2_float, 'ro')

plt.legend()
plt.grid()
plt.title("Question 1a")
plt.show()